name: CI

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Cache node_modules
      - name: Setup Node.js and cache pnpm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Lint
        run: pnpm nx run-many -t lint

      - name: Build
        run: pnpm nx build web

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web/build'

      - name: Upload to github pages
        uses: actions/deploy-pages@v4
